import { TweetsSection } from '@/components/ui/tweetsSection/TweetsSection'
import Head from 'next/head'
import { useSession } from 'next-auth/react'
import { ScreenProtector } from '@/components/ui/screenProtector/ScreenProtector'
import { useContext } from 'react'
import { WriteTweetModalContext } from '@/contexts/WriteTweetModalContext'
import { TweetModal } from '@/components/ui/modals/TweetModal'
import { useGetTweets } from '@/hooks/useGetTweets'
import { Layout } from '@/components/ui/Layout'

export default function Home () {
  const { status } = useSession()

  const { state } = useContext(WriteTweetModalContext)
  const { sectionSelected, setSectionSelected, tweets, addTweet, error, isLoading } = useGetTweets()

  return (
    <>
      <Head>
        <title>y4nzz | Twitter Clone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {
        status === 'loading' && <ScreenProtector />
      }
      {
        state.open === true && <TweetModal addTweet={addTweet} />
      }
        <TweetsSection
          sectionSelected={sectionSelected}
          setSectionSelected={setSectionSelected}
          tweets={tweets}
          addTweet={addTweet}
          error={error}
          isLoading={isLoading}
        />
    </>
  )
}

Home.getLayout = (page) => {
  return <Layout>
    {page}
  </Layout>
}
